server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/gch
    username: gch
    password: gch
  jpa:
    hibernate:
      ddl-auto: validate # Liquibase
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework.security: INFO
